//
//  ScanBarcodePresenter.swift
//  MyFridge
//
//  Created by Lars Dahl on 01.06.2018.
//  Copyright (c) 2018 Lars Dahl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScanBarcodePresentationLogic {
    func showBarcode(response: ScanBarcode.Response)
}

class ScanBarcodePresenter: ScanBarcodePresentationLogic {
    weak var viewController: ScanBarcodeDisplayLogic?
  
    // MARK: Do something
  
    func showBarcode(response: ScanBarcode.Response) {
        var viewModel = ScanBarcode.ViewModel()
        viewModel.barcodeValue = response.data.value
        
        DispatchQueue.main.async {
            self.viewController?.displayBarcode(viewModel: viewModel)
        }
    }
}
